/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Addresses } from '../models/addresses';
import { CustomError } from '../models/customError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { AddressServiceInterface }                            from './address.serviceInterface';


@Injectable({
  providedIn: 'root'
})
export class AddressService implements AddressServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Delete user&#39;s address
     * @param Token user token
     * @param LANG user LANG
     * @param AddressId Address&#39; id.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public delAddress(Token: string, LANG: string, AddressId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public delAddress(Token: string, LANG: string, AddressId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public delAddress(Token: string, LANG: string, AddressId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public delAddress(Token: string, LANG: string, AddressId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling delAddress.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling delAddress.');
        }

        if (AddressId === null || AddressId === undefined) {
            throw new Error('Required parameter AddressId was null or undefined when calling delAddress.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (AddressId !== undefined && AddressId !== null) {
            queryParameters = queryParameters.set('AddressId', <any>AddressId);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.delete<string>(`${this.basePath}/address`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get user&#39;s addresses
     *  get adress
     * @param Token user token
     * @param LANG user LANG
     * @param RefClient Only for techniciens.
     * @param AddressId Address&#39; id.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAddress(Token: string, LANG: string, RefClient?: string, AddressId?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Addresses>>;
    public getAddress(Token: string, LANG: string, RefClient?: string, AddressId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Addresses>>>;
    public getAddress(Token: string, LANG: string, RefClient?: string, AddressId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Addresses>>>;
    public getAddress(Token: string, LANG: string, RefClient?: string, AddressId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling getAddress.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling getAddress.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (RefClient !== undefined && RefClient !== null) {
            queryParameters = queryParameters.set('RefClient', <any>RefClient);
        }
        if (AddressId !== undefined && AddressId !== null) {
            queryParameters = queryParameters.set('AddressId', <any>AddressId);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Array<Addresses>>(`${this.basePath}/address`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update registered address.
     * Update an existing address.
     * @param Token user token
     * @param LANG user LANG
     * @param address Address data
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putAddress(Token: string, LANG: string, address: Addresses, observe?: 'body', reportProgress?: boolean): Observable<Addresses>;
    public putAddress(Token: string, LANG: string, address: Addresses, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Addresses>>;
    public putAddress(Token: string, LANG: string, address: Addresses, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Addresses>>;
    public putAddress(Token: string, LANG: string, address: Addresses, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling putAddress.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling putAddress.');
        }

        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling putAddress.');
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Addresses>(`${this.basePath}/address`,
            address,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Submit a new user&#39;s address.
     * Submit a new user&#39;s address.
     * @param Token user token
     * @param LANG user LANG
     * @param address Address data
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setAddress(Token: string, LANG: string, address: Addresses, observe?: 'body', reportProgress?: boolean): Observable<Addresses>;
    public setAddress(Token: string, LANG: string, address: Addresses, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Addresses>>;
    public setAddress(Token: string, LANG: string, address: Addresses, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Addresses>>;
    public setAddress(Token: string, LANG: string, address: Addresses, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling setAddress.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling setAddress.');
        }

        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling setAddress.');
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Addresses>(`${this.basePath}/address`,
            address,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
