/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Addresses } from '../models/addresses';
import { CustomError } from '../models/customError';


import { Configuration }                                     from '../configuration';


export interface AddressServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * Delete user&#39;s address
    * @param Token user token
    * @param LANG user LANG
    * @param AddressId Address&#39; id.
    */
    delAddress(Token: string, LANG: string, AddressId: string, extraHttpRequestParams?: any): Observable<string>;

    /**
    * Get user&#39;s addresses
    *  get adress
    * @param Token user token
    * @param LANG user LANG
    * @param RefClient Only for techniciens.
    * @param AddressId Address&#39; id.
    */
    getAddress(Token: string, LANG: string, RefClient?: string, AddressId?: number, extraHttpRequestParams?: any): Observable<Array<Addresses>>;

    /**
    * Update registered address.
    * Update an existing address.
    * @param Token user token
    * @param LANG user LANG
    * @param address Address data
    */
    putAddress(Token: string, LANG: string, address: Addresses, extraHttpRequestParams?: any): Observable<Addresses>;

    /**
    * Submit a new user&#39;s address.
    * Submit a new user&#39;s address.
    * @param Token user token
    * @param LANG user LANG
    * @param address Address data
    */
    setAddress(Token: string, LANG: string, address: Addresses, extraHttpRequestParams?: any): Observable<Addresses>;

}
