/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CartItems } from '../models/cartItems';
import { Carts } from '../models/carts';
import { CustomError } from '../models/customError';


import { Configuration }                                     from '../configuration';


export interface CartServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Add item (existing or not) to cart.
    * Add item (existing or not) to cart.
    * @param Token user token
    * @param LANG user LANG
    * @param Item identifiant produit à ajouter
    */
    addProduct(Token: string, LANG: string, Item: CartItems, extraHttpRequestParams?: any): Observable<Carts>;

    /**
    * Delete item from cart.
    * Delete item from cart.
    * @param Token user token
    * @param LANG user LANG
    * @param RefArticle Article&#39;s reference.
    */
    delProductCart(Token: string, LANG: string, RefArticle: string, extraHttpRequestParams?: any): Observable<Carts>;

    /**
    * Get cart&#39;s info
    * Get cart&#39;s info
    * @param Token user token
    * @param LANG user LANG
    */
    getCart(Token: string, LANG: string, extraHttpRequestParams?: any): Observable<Carts>;

}
