/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Consuptions } from '../models/consuptions';
import { CustomError } from '../models/customError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { ConsuptionsServiceInterface }                            from './consuptions.serviceInterface';


@Injectable({
  providedIn: 'root'
})
export class ConsuptionsService implements ConsuptionsServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get clients&#39; consuptions.
     * Get clients&#39; consuptions.
     * @param Token user token
     * @param LANG user LANG
     * @param RefClient 
     * @param DateVente Selling&#39;s Day. Format: YYYY-MM-DD
     * @param RefArticle 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getConsuptions(Token: string, LANG: string, RefClient?: string, DateVente?: string, RefArticle?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Consuptions>>;
    public getConsuptions(Token: string, LANG: string, RefClient?: string, DateVente?: string, RefArticle?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Consuptions>>>;
    public getConsuptions(Token: string, LANG: string, RefClient?: string, DateVente?: string, RefArticle?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Consuptions>>>;
    public getConsuptions(Token: string, LANG: string, RefClient?: string, DateVente?: string, RefArticle?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling getConsuptions.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling getConsuptions.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (RefClient !== undefined && RefClient !== null) {
            queryParameters = queryParameters.set('RefClient', <any>RefClient);
        }
        if (DateVente !== undefined && DateVente !== null) {
            queryParameters = queryParameters.set('DateVente', <any>DateVente);
        }
        if (RefArticle !== undefined && RefArticle !== null) {
            queryParameters = queryParameters.set('RefArticle', <any>RefArticle);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Array<Consuptions>>(`${this.basePath}/consuptions`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
