/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../models/customError';


import { Configuration }                                     from '../configuration';


export interface EmailServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Change user email.
    * Change user email
    * @param LANG user LANG
    * @param email User&#39;s email
    */
    changeEmail(LANG: string, email: string, extraHttpRequestParams?: any): Observable<string>;

    /**
    * 
    * CheckEmail
    * @param token Key to reset password
    * @param email account email
    */
    checkEmail(token: string, email: string, extraHttpRequestParams?: any): Observable<string>;

    /**
    * 
    * Send email verification
    * @param email account email
    */
    sendEmailVerification(email: string, extraHttpRequestParams?: any): Observable<string>;

}
