/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../models/customError';
import { Locations } from '../models/locations';
import { Machines } from '../models/machines';


import { Configuration }                                     from '../configuration';


export interface MachinesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Get all machines with its respective contract filtered by values provided.
    * Get all machines filtered by values provided.
    * @param Token user token
    * @param LANG user LANG
    * @param RefContract 
    * @param RefArticle 
    * @param MachineId 
    * @param NumSerie 
    * @param RefClient 
    */
    getListLocations(Token: string, LANG: string, RefContract?: string, RefArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, extraHttpRequestParams?: any): Observable<Array<Locations>>;

    /**
    * Get all Pieces filtered by values provided.
    * Get all Pieces filtered by values provided.
    * @param Token user token
    * @param LANG user LANG
    * @param RefArticle 
    * @param DesignationArticle 
    * @param MachineId 
    * @param NumSerie 
    * @param RefClient 
    */
    getListMachines(Token: string, LANG: string, RefArticle?: string, DesignationArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, extraHttpRequestParams?: any): Observable<Array<Machines>>;

}
