/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../models/customError';
import { Locations } from '../models/locations';
import { Machines } from '../models/machines';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { MachinesServiceInterface }                            from './machines.serviceInterface';


@Injectable({
  providedIn: 'root'
})
export class MachinesService implements MachinesServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get all machines with its respective contract filtered by values provided.
     * Get all machines filtered by values provided.
     * @param Token user token
     * @param LANG user LANG
     * @param RefContract 
     * @param RefArticle 
     * @param MachineId 
     * @param NumSerie 
     * @param RefClient 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getListLocations(Token: string, LANG: string, RefContract?: string, RefArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Locations>>;
    public getListLocations(Token: string, LANG: string, RefContract?: string, RefArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Locations>>>;
    public getListLocations(Token: string, LANG: string, RefContract?: string, RefArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Locations>>>;
    public getListLocations(Token: string, LANG: string, RefContract?: string, RefArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling getListLocations.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling getListLocations.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (RefContract !== undefined && RefContract !== null) {
            queryParameters = queryParameters.set('RefContract', <any>RefContract);
        }
        if (RefArticle !== undefined && RefArticle !== null) {
            queryParameters = queryParameters.set('RefArticle', <any>RefArticle);
        }
        if (MachineId !== undefined && MachineId !== null) {
            queryParameters = queryParameters.set('MachineId', <any>MachineId);
        }
        if (NumSerie !== undefined && NumSerie !== null) {
            queryParameters = queryParameters.set('NumSerie', <any>NumSerie);
        }
        if (RefClient !== undefined && RefClient !== null) {
            queryParameters = queryParameters.set('RefClient', <any>RefClient);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Array<Locations>>(`${this.basePath}/locations`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all Pieces filtered by values provided.
     * Get all Pieces filtered by values provided.
     * @param Token user token
     * @param LANG user LANG
     * @param RefArticle 
     * @param DesignationArticle 
     * @param MachineId 
     * @param NumSerie 
     * @param RefClient 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getListMachines(Token: string, LANG: string, RefArticle?: string, DesignationArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Machines>>;
    public getListMachines(Token: string, LANG: string, RefArticle?: string, DesignationArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Machines>>>;
    public getListMachines(Token: string, LANG: string, RefArticle?: string, DesignationArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Machines>>>;
    public getListMachines(Token: string, LANG: string, RefArticle?: string, DesignationArticle?: string, MachineId?: number, NumSerie?: string, RefClient?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling getListMachines.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling getListMachines.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (RefArticle !== undefined && RefArticle !== null) {
            queryParameters = queryParameters.set('RefArticle', <any>RefArticle);
        }
        if (DesignationArticle !== undefined && DesignationArticle !== null) {
            queryParameters = queryParameters.set('DesignationArticle', <any>DesignationArticle);
        }
        if (MachineId !== undefined && MachineId !== null) {
            queryParameters = queryParameters.set('MachineId', <any>MachineId);
        }
        if (NumSerie !== undefined && NumSerie !== null) {
            queryParameters = queryParameters.set('NumSerie', <any>NumSerie);
        }
        if (RefClient !== undefined && RefClient !== null) {
            queryParameters = queryParameters.set('RefClient', <any>RefClient);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Array<Machines>>(`${this.basePath}/machines`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
