/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../models/customError';


import { Configuration }                                     from '../configuration';


export interface PasswordServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Change password by providing old password.
    * change user password
    * @param LANG user LANG
    * @param passwordOld Old password
    * @param passwordNew Old password
    */
    changePasswordWithOldPassword(LANG: string, passwordOld: string, passwordNew: string, extraHttpRequestParams?: any): Observable<string>;

    /**
    * Change password by providing email&#39;s token.
    * Request a new password with forget token.
    * @param newPassword Forgot password token
    */
    changePasswordWithToken(newPassword: string, extraHttpRequestParams?: any): Observable<string>;

    /**
    * Send email to user who lost password
    * forgotPassword
    * @param LANG user LANG
    * @param email User&#39;s email
    * @param killSessions If session&#39;s asociated with that email must be cleared.
    */
    forgotPasswordClient(LANG: string, email: string, killSessions: boolean, extraHttpRequestParams?: any): Observable<string>;

}
