/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../models/customError';
import { Session } from '../models/session';
import { Users } from '../models/users';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { UserServiceInterface }                            from './user.serviceInterface';


@Injectable({
  providedIn: 'root'
})
export class UserService implements UserServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Change user email.
     * Change user email
     * @param LANG user LANG
     * @param email User&#39;s email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changeEmail(LANG: string, email: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public changeEmail(LANG: string, email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public changeEmail(LANG: string, email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public changeEmail(LANG: string, email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling changeEmail.');
        }

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling changeEmail.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }

        let headers = this.defaultHeaders;
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.post<string>(`${this.basePath}/user/email/change`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Change password by providing old password.
     * change user password
     * @param LANG user LANG
     * @param passwordOld Old password
     * @param passwordNew Old password
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changePasswordWithOldPassword(LANG: string, passwordOld: string, passwordNew: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public changePasswordWithOldPassword(LANG: string, passwordOld: string, passwordNew: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public changePasswordWithOldPassword(LANG: string, passwordOld: string, passwordNew: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public changePasswordWithOldPassword(LANG: string, passwordOld: string, passwordNew: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling changePasswordWithOldPassword.');
        }

        if (passwordOld === null || passwordOld === undefined) {
            throw new Error('Required parameter passwordOld was null or undefined when calling changePasswordWithOldPassword.');
        }

        if (passwordNew === null || passwordNew === undefined) {
            throw new Error('Required parameter passwordNew was null or undefined when calling changePasswordWithOldPassword.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (passwordOld !== undefined && passwordOld !== null) {
            queryParameters = queryParameters.set('passwordOld', <any>passwordOld);
        }
        if (passwordNew !== undefined && passwordNew !== null) {
            queryParameters = queryParameters.set('passwordNew', <any>passwordNew);
        }

        let headers = this.defaultHeaders;
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.patch<string>(`${this.basePath}/user/password`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Change password by providing email&#39;s token.
     * Request a new password with forget token.
     * @param newPassword Forgot password token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changePasswordWithToken(newPassword: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public changePasswordWithToken(newPassword: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public changePasswordWithToken(newPassword: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public changePasswordWithToken(newPassword: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (newPassword === null || newPassword === undefined) {
            throw new Error('Required parameter newPassword was null or undefined when calling changePasswordWithToken.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (newPassword !== undefined && newPassword !== null) {
            queryParameters = queryParameters.set('newPassword', <any>newPassword);
        }

        let headers = this.defaultHeaders;

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<string>(`${this.basePath}/user/password`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * CheckEmail
     * @param token Key to reset password
     * @param email account email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public checkEmail(token: string, email: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public checkEmail(token: string, email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public checkEmail(token: string, email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public checkEmail(token: string, email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (token === null || token === undefined) {
            throw new Error('Required parameter token was null or undefined when calling checkEmail.');
        }

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling checkEmail.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }

        let headers = this.defaultHeaders;

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<string>(`${this.basePath}/user/email/check`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Callback from facebook auth.
     * Get the user parameters.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public facebookCallback(observe?: 'body', reportProgress?: boolean): Observable<Session>;
    public facebookCallback(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Session>>;
    public facebookCallback(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Session>>;
    public facebookCallback(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Session>(`${this.basePath}/user/login/facebook/callback`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send email to user who lost password
     * forgotPassword
     * @param LANG user LANG
     * @param email User&#39;s email
     * @param killSessions If session&#39;s asociated with that email must be cleared.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public forgotPasswordClient(LANG: string, email: string, killSessions: boolean, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public forgotPasswordClient(LANG: string, email: string, killSessions: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public forgotPasswordClient(LANG: string, email: string, killSessions: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public forgotPasswordClient(LANG: string, email: string, killSessions: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling forgotPasswordClient.');
        }

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling forgotPasswordClient.');
        }

        if (killSessions === null || killSessions === undefined) {
            throw new Error('Required parameter killSessions was null or undefined when calling forgotPasswordClient.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }
        if (killSessions !== undefined && killSessions !== null) {
            queryParameters = queryParameters.set('killSessions', <any>killSessions);
        }

        let headers = this.defaultHeaders;
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.post<string>(`${this.basePath}/user/password/forgot`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get client&#39;s information.
     * get profile info
     * @param Token user token
     * @param LANG user LANG
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProfile(Token: string, LANG: string, observe?: 'body', reportProgress?: boolean): Observable<Users>;
    public getProfile(Token: string, LANG: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Users>>;
    public getProfile(Token: string, LANG: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Users>>;
    public getProfile(Token: string, LANG: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling getProfile.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling getProfile.');
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Users>(`${this.basePath}/user`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Login by email and password.
     * Login
     * @param LANG user LANG
     * @param email User&#39;s email.
     * @param password User&#39;s password.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public login(LANG: string, email: string, password: string, observe?: 'body', reportProgress?: boolean): Observable<Session>;
    public login(LANG: string, email: string, password: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Session>>;
    public login(LANG: string, email: string, password: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Session>>;
    public login(LANG: string, email: string, password: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling login.');
        }

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling login.');
        }

        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling login.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('password', <any>password);
        }

        let headers = this.defaultHeaders;
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Session>(`${this.basePath}/user/login`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Login by Facebook account.
     * URL to redirect to facebook page.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public loginFacebook(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public loginFacebook(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public loginFacebook(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public loginFacebook(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<any>(`${this.basePath}/user/login/facebook`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Google token
     * getting user details from G
     * @param Token user token
     * @param LANG user LANG
     * @param Googletoken Googletoken
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public loginGoogle(Token: string, LANG: string, Googletoken: string, observe?: 'body', reportProgress?: boolean): Observable<Session>;
    public loginGoogle(Token: string, LANG: string, Googletoken: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Session>>;
    public loginGoogle(Token: string, LANG: string, Googletoken: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Session>>;
    public loginGoogle(Token: string, LANG: string, Googletoken: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling loginGoogle.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling loginGoogle.');
        }

        if (Googletoken === null || Googletoken === undefined) {
            throw new Error('Required parameter Googletoken was null or undefined when calling loginGoogle.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Googletoken !== undefined && Googletoken !== null) {
            queryParameters = queryParameters.set('Googletoken', <any>Googletoken);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Session>(`${this.basePath}/user/login/google`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update client&#39;s information.
     * change profile info
     * @param LANG user LANG
     * @param User User details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putProfile(LANG: string, User: Users, observe?: 'body', reportProgress?: boolean): Observable<Users>;
    public putProfile(LANG: string, User: Users, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Users>>;
    public putProfile(LANG: string, User: Users, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Users>>;
    public putProfile(LANG: string, User: Users, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling putProfile.');
        }

        if (User === null || User === undefined) {
            throw new Error('Required parameter User was null or undefined when calling putProfile.');
        }

        let headers = this.defaultHeaders;
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Users>(`${this.basePath}/user`,
            User,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Send email verification
     * @param email account email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendEmailVerification(email: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public sendEmailVerification(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public sendEmailVerification(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public sendEmailVerification(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling sendEmailVerification.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }

        let headers = this.defaultHeaders;

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.post<string>(`${this.basePath}/user/email/send`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Register User
     * Registration
     * @param LANG user LANG
     * @param User User&#39;s data
     * @param Password User&#39;s password.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setProfile(LANG: string, User: Users, Password: string, observe?: 'body', reportProgress?: boolean): Observable<Users>;
    public setProfile(LANG: string, User: Users, Password: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Users>>;
    public setProfile(LANG: string, User: Users, Password: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Users>>;
    public setProfile(LANG: string, User: Users, Password: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling setProfile.');
        }

        if (User === null || User === undefined) {
            throw new Error('Required parameter User was null or undefined when calling setProfile.');
        }

        if (Password === null || Password === undefined) {
            throw new Error('Required parameter Password was null or undefined when calling setProfile.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Password !== undefined && Password !== null) {
            queryParameters = queryParameters.set('Password', <any>Password);
        }

        let headers = this.defaultHeaders;
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Users>(`${this.basePath}/user`,
            User,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Provide Session Token
     *  Provide Session Token and user.Name, NumberOfCartElements, user.refclient
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public startSession(observe?: 'body', reportProgress?: boolean): Observable<Session>;
    public startSession(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Session>>;
    public startSession(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Session>>;
    public startSession(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.post<Session>(`${this.basePath}/user/verifyToken`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
