/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../models/customError';
import { Visites } from '../models/visites';


import { Configuration }                                     from '../configuration';


export interface VisitesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Get Visites to be done filtered by values provided.
    * Get Visites to be done filtered by values provided.
    * @param Token user token
    * @param LANG user LANG
    * @param TechnicienId 
    * @param ClientsAddressId 
    * @param RefClient 
    * @param DateVisite Format: YYYY-MM-DD HH:mm:ss Z.
    * @param MachineId Machine&#39;s id.
    */
    getListNextVisites(Token: string, LANG: string, TechnicienId?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, extraHttpRequestParams?: any): Observable<Array<Visites>>;

    /**
    * Get all Visites filtered by values provided.
    * Get all Visites filtered by values provided.
    * @param Token user token
    * @param LANG user LANG
    * @param TechnicienId 
    * @param Visitid 
    * @param ClientsAddressId 
    * @param RefClient 
    * @param DateVisite Format: YYYY-MM-DD HH:mm:ss Z.
    * @param MachineId Machine&#39;s id.
    */
    getListVisites(Token: string, LANG: string, TechnicienId?: number, Visitid?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, extraHttpRequestParams?: any): Observable<Array<Visites>>;

    /**
    * Modify existing Visite.
    * Modify existing Visite.
    * @param Token user token
    * @param LANG user LANG
    * @param Visite Visite object
    */
    putVisite(Token: string, LANG: string, Visite: Visites, extraHttpRequestParams?: any): Observable<Visites>;

    /**
    * Add new Visite.
    * Add new Visite.
    * @param Token user token
    * @param LANG user LANG
    * @param Visite Visite object
    */
    setVisite(Token: string, LANG: string, Visite: Visites, extraHttpRequestParams?: any): Observable<Visites>;

}
