/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CustomError } from '../models/customError';
import { Visites } from '../models/visites';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { VisitesServiceInterface }                            from './visites.serviceInterface';


@Injectable({
  providedIn: 'root'
})
export class VisitesService implements VisitesServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get Visites to be done filtered by values provided.
     * Get Visites to be done filtered by values provided.
     * @param Token user token
     * @param LANG user LANG
     * @param TechnicienId 
     * @param ClientsAddressId 
     * @param RefClient 
     * @param DateVisite Format: YYYY-MM-DD HH:mm:ss Z.
     * @param MachineId Machine&#39;s id.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getListNextVisites(Token: string, LANG: string, TechnicienId?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Visites>>;
    public getListNextVisites(Token: string, LANG: string, TechnicienId?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Visites>>>;
    public getListNextVisites(Token: string, LANG: string, TechnicienId?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Visites>>>;
    public getListNextVisites(Token: string, LANG: string, TechnicienId?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling getListNextVisites.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling getListNextVisites.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (TechnicienId !== undefined && TechnicienId !== null) {
            queryParameters = queryParameters.set('TechnicienId', <any>TechnicienId);
        }
        if (ClientsAddressId !== undefined && ClientsAddressId !== null) {
            queryParameters = queryParameters.set('ClientsAddressId', <any>ClientsAddressId);
        }
        if (RefClient !== undefined && RefClient !== null) {
            queryParameters = queryParameters.set('RefClient', <any>RefClient);
        }
        if (DateVisite !== undefined && DateVisite !== null) {
            queryParameters = queryParameters.set('DateVisite', <any>DateVisite);
        }
        if (MachineId !== undefined && MachineId !== null) {
            queryParameters = queryParameters.set('MachineId', <any>MachineId);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Array<Visites>>(`${this.basePath}/visites/next`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all Visites filtered by values provided.
     * Get all Visites filtered by values provided.
     * @param Token user token
     * @param LANG user LANG
     * @param TechnicienId 
     * @param Visitid 
     * @param ClientsAddressId 
     * @param RefClient 
     * @param DateVisite Format: YYYY-MM-DD HH:mm:ss Z.
     * @param MachineId Machine&#39;s id.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getListVisites(Token: string, LANG: string, TechnicienId?: number, Visitid?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Visites>>;
    public getListVisites(Token: string, LANG: string, TechnicienId?: number, Visitid?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Visites>>>;
    public getListVisites(Token: string, LANG: string, TechnicienId?: number, Visitid?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Visites>>>;
    public getListVisites(Token: string, LANG: string, TechnicienId?: number, Visitid?: number, ClientsAddressId?: number, RefClient?: string, DateVisite?: string, MachineId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling getListVisites.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling getListVisites.');
        }







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (TechnicienId !== undefined && TechnicienId !== null) {
            queryParameters = queryParameters.set('TechnicienId', <any>TechnicienId);
        }
        if (Visitid !== undefined && Visitid !== null) {
            queryParameters = queryParameters.set('Visitid', <any>Visitid);
        }
        if (ClientsAddressId !== undefined && ClientsAddressId !== null) {
            queryParameters = queryParameters.set('ClientsAddressId', <any>ClientsAddressId);
        }
        if (RefClient !== undefined && RefClient !== null) {
            queryParameters = queryParameters.set('RefClient', <any>RefClient);
        }
        if (DateVisite !== undefined && DateVisite !== null) {
            queryParameters = queryParameters.set('DateVisite', <any>DateVisite);
        }
        if (MachineId !== undefined && MachineId !== null) {
            queryParameters = queryParameters.set('MachineId', <any>MachineId);
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];

        return this.httpClient.get<Array<Visites>>(`${this.basePath}/visites`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Modify existing Visite.
     * Modify existing Visite.
     * @param Token user token
     * @param LANG user LANG
     * @param Visite Visite object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putVisite(Token: string, LANG: string, Visite: Visites, observe?: 'body', reportProgress?: boolean): Observable<Visites>;
    public putVisite(Token: string, LANG: string, Visite: Visites, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Visites>>;
    public putVisite(Token: string, LANG: string, Visite: Visites, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Visites>>;
    public putVisite(Token: string, LANG: string, Visite: Visites, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling putVisite.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling putVisite.');
        }

        if (Visite === null || Visite === undefined) {
            throw new Error('Required parameter Visite was null or undefined when calling putVisite.');
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Visites>(`${this.basePath}/visites`,
            Visite,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add new Visite.
     * Add new Visite.
     * @param Token user token
     * @param LANG user LANG
     * @param Visite Visite object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setVisite(Token: string, LANG: string, Visite: Visites, observe?: 'body', reportProgress?: boolean): Observable<Visites>;
    public setVisite(Token: string, LANG: string, Visite: Visites, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Visites>>;
    public setVisite(Token: string, LANG: string, Visite: Visites, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Visites>>;
    public setVisite(Token: string, LANG: string, Visite: Visites, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (Token === null || Token === undefined) {
            throw new Error('Required parameter Token was null or undefined when calling setVisite.');
        }

        if (LANG === null || LANG === undefined) {
            throw new Error('Required parameter LANG was null or undefined when calling setVisite.');
        }

        if (Visite === null || Visite === undefined) {
            throw new Error('Required parameter Visite was null or undefined when calling setVisite.');
        }

        let headers = this.defaultHeaders;
        if (Token !== undefined && Token !== null) {
            headers = headers.set('Token', String(Token));
        }
        if (LANG !== undefined && LANG !== null) {
            headers = headers.set('LANG', String(LANG));
        }

        // authentication (appToken) required
        if (this.configuration.apiKeys["X_APP_ID"]) {
            headers = headers.set('X_APP_ID', this.configuration.apiKeys["X_APP_ID"]);
        }

        // authentication (userToken) required
        if (this.configuration.apiKeys["X_USER_KEY"]) {
            headers = headers.set('X_USER_KEY', this.configuration.apiKeys["X_USER_KEY"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Visites>(`${this.basePath}/visites`,
            Visite,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
