/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Clients } from './clients';


export interface Addresses { 
    id?: number;
    client?: Clients;
    name?: string;
    numero?: string;
    address?: string;
    codePostal?: number;
    complement?: string;
    ville?: string;
    pays?: string;
    telephone?: string;
    nom?: string;
    livraison?: string;
    latitude?: number;
    longitude?: number;
    typeAddress?: string;
}
