/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Carts } from './carts';
import { Pieces } from './pieces';


export interface CartItems { 
    id?: number;
    piece?: Pieces;
    cart?: Carts;
    pu?: number;
    pt?: number;
    remise?: number;
    quantite?: number;
}
