/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Clients { 
    refClient?: string;
    abrege?: string;
    prenom?: string;
    nom?: string;
    etat?: string;
    groupe?: string;
    statutGroupe?: string;
    statut?: string;
    raisonSociale?: string;
    typeClient?: string;
    score?: number;
    secteur?: number;
    frequence?: number;
    email?: string;
    interdit?: boolean;
    lastSuccessfulAttempt?: Date;
    idFacebook?: string;
    idGoogle?: string;
    siret?: string;
    tvaIntraco?: string;
    civilite?: string;
    nbConnectionAttempt?: number;
    validationKey?: string;
}
