/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Clients } from './clients';
import { Pieces } from './pieces';


export interface Consuptions { 
    id?: number;
    client?: Clients;
    piece?: Pieces;
    qte?: number;
    ca?: number;
    dateVente?: Date;
}
