/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Clients } from './clients';
import { Machines } from './machines';


export interface Contracts { 
    refContract?: number;
    machines?: Array<Machines>;
    client?: Clients;
    dateDebut?: string;
    dateFin?: string;
    reconduction?: string;
    loyer?: number;
    miniconso?: number;
}
