/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pieces } from './pieces';
import { PiecesDetail } from './piecesDetail';
import { PiecesFiche } from './piecesFiche';
import { PiecesKeyPoints } from './piecesKeyPoints';


export interface Products { 
    piece?: Pieces;
    piecesFiche?: PiecesFiche;
    piecesKeyPoints?: Array<PiecesKeyPoints>;
    piecesDetail?: Array<PiecesDetail>;
}
