/**
 * Ravimo Global API
 * Ravimo Mobile and Web Global API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joseph.assouline@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Addresses } from './addresses';
import { Machines } from './machines';
import { ZoneResas } from './zoneResas';


export interface Visites { 
    id: number;
    machine?: Machines;
    zoneResa?: ZoneResas;
    clientsAddress?: Addresses;
    dateVisite?: string;
    th?: number;
    temperatureLavage?: number;
    temperatureRincage?: number;
    conductivite?: number;
    commentaire?: string;
}
